label_inventory/config/routes.rb
LabelInventory::Application.routes.draw do

  resources :users do
    collection do
      get 'activate'
    end
  end
  resource :session, only: [:create, :destroy, :new]

  resources :bands do
    resources :albums, only: [:new, :create, :index]
    resources :tracks, only: [:new, :create, :index]
  end

  resources :tracks, only: [:show, :destroy, :update, :edit] do
    resources :notes, only: [:show, :new, :create]
  end

  resources :notes, only: [:destroy]
  resources :albums, only: [:show, :destroy, :update, :edit]

  root to: 'bands#index'
end

label_inventory/app/models/album.rb
class Album < ActiveRecord::Base
  validates :title, :band_id, :setting, presence: true
  validates :setting, inclusion: { in: %w{ Live Studio } }
  belongs_to :band
  has_many :recordings, class_name: "Track", foreign_key: :album_id
  validates :title, uniqueness: { scope: :band_id }
end

label_inventory/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def new
    @album = Album.new
    @band = Band.find(params[:band_id])
    @bands = Band.all
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      redirect_to new_band_album_url
    end
  end

  def index
    @albums = Album.all
  end

  def show
    @album = Album.find(params[:id])
  end

  def edit
    @bands = Band.all
    @album = Album.find params[:id]
    @band = @album.band
  end

  def update
    @album = Album.find(params[:id])
    @album.update(album_params)

    render :show
  end

  def destroy
    @album = Album.find(params[:id])
    @band = @album.band
    @album.destroy
    redirect_to band_url(@band)
  end


  private

  def album_params
    params.require(:album).permit(:band_id, :title, :setting)
  end
end

label_inventory/app/helpers/albums_helper.rb
module AlbumsHelper
end

label_inventory/app/views/albums/_form.html.erb
<% if @album.persisted? %>
  <% action = album_url(@album) %>
  <% submit_val = "Edit Album" %>
<% else %>
  <% action = band_albums_url %>
  <% submit_val = "Add Album" %>
<% end %>


<form action="<%= action %>" method="post">
  <% if @album.persisted?%>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  <input type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">


  <label for="album_band"><h2>Select a Band:</h2></label>

  <select name="album[band_id]" id="album_band">
    <% @bands.each do |band| %>
      <option value="<%= band.id %>"
        <%= selected="selected" if band.id == @band.id%>
        <% if @band.name == band.name %>
         selected
        <% end %>>
      <%= band.name %>
      </option>
    <% end %>
  </select>

  <br>

  <label for="album_title"><h2>Album Title</h2>
  <input
    type="text"
    name="album[title]"
    id="album_title"
    value="<%= @album.title %>">

  <br>

  <p><h2>Pick an Album Setting:</p></h2>
  <label for="album_setting_live">Live Album</label>
  <input
    type="radio"
    name="album[setting]"
    id="album_setting"
    value="Live"
    <% if @album.setting == "Live" %>
      checked="true"
    <% end %>>

  <br>

  <label for="album_setting_studio">Studio Album</label>
  <input type="radio"
    name="album[setting]"
    id="album_setting_studio"
    <% if @album.setting == "Studio" %>
    checked="true"
    <% end %>
    value="Studio">


  <br>
  <input type="submit" value="<%= submit_val %>">

</form>

label_inventory/app/views/albums/edit.html.erb
<h1>Edit an Album</h1>


<%= render "form" %>

label_inventory/app/views/albums/new.html.erb
<h1>Add a new Album</h1>


<%= render "form" %>

label_inventory/app/views/albums/show.html.erb
<h1>Album <%= @album.title %></h1>

<p>Band: <a href="<%= band_url(@album.band) %>"><%= @album.band.name %></a></p>

<h2>Tracks:</h2>
<ul>
  <% @album.recordings.each do |track| %>
    <li><a href="<%= track_url(track) %>"><%= track.title %></a></li>
  <% end %>
</ul>

<h2>Setting</h2>
<strong><%= @album.setting %></strong>

<br><br>


<a href="<%= new_band_track_url(@album.band) %>">Add a Track to this Band</a>

<br><br>

<a href="<%= edit_album_path(@album) %>">Edit Album</a>

<form action="<%= album_url(@album) %>" method="post">
  <input type="hidden" name="_method" value="delete">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="submit" value="Delete this Album">

</form>