label_inventory/config/routes.rb
LabelInventory::Application.routes.draw do

  resources :users do
    collection do
      get 'activate'
    end
  end
  resource :session, only: [:create, :destroy, :new]

  resources :bands do
    resources :albums, only: [:new, :create, :index]
    resources :tracks, only: [:new, :create, :index]
  end

  resources :tracks, only: [:show, :destroy, :update, :edit] do
    resources :notes, only: [:show, :new, :create]
  end

  resources :notes, only: [:destroy]
  resources :albums, only: [:show, :destroy, :update, :edit]

  root to: 'bands#index'
end

label_inventory/app/models/track.rb
class Track < ActiveRecord::Base
  validates :title, :album_id, presence: true
  validates :title, uniqueness: { scope: :album_id }
  validates :status, inclusion: { in: %w{ Regular Bonus } }
  belongs_to :album
  has_many :notes

  delegate :band, to: :album

end

label_inventory/app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def new
    @band = Band.find params[:band_id]
    @track = Track.new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to track_url(@track)
    else
      flash[:errors] = @track.errors.full_messages
      redirect_to new_band_track_url
    end
  end

  def index
    @track = Track.find(params[:id])
  end

  def update
    @track = Track.find(params[:id])
    if @track.update(track_params)
      render :show
    else
      flash[:errors] = @track.errors.full_messages
      redirect_to edit_track_url(@track)
    end
  end

  def show
    @track = Track.find params[:id]
  end

  def edit
    @track = Track.find params[:id]
    @album = @track.album
    @band = @track.band
  end

  def destroy
    track = Track.find params[:id]
    @album = track.album
    track.destroy
    redirect_to album_url(@album)
  end


  private

  def track_params
    params.require(:track).permit(:title, :lyrics, :album_id, :status)
  end
end

label_inventory/app/helpers/tracks_helper.rb
module TracksHelper
end

label_inventory/app/views/tracks/_form.html.erb
<% if @track.persisted? %>
    <% action = track_url(@track)%>
    <% submit_val = "Edit Track" %>
  <% else %>
    <% action = band_tracks_url %>
    <% submit_val = "Add Track" %>
<% end %>

<form action="<%= action %>" method="post">
  <% if @track.persisted?%>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <br><br>

  <label for="track_album"></h2>Pick an Album</h2></label>
  <select name="track[album_id]" id="track_album">

    <% @band.albums.each do |album| %>

      <option
        name="track[album_id]"
        value="<%= album.id %>"
        <% if @album && album.title == @album.title %>
         selected
        <% end %>>
        <%= album.title %>
      </option>

    <% end %>
  </select>

  <br><br>

  <label for="track_title"><h2>Title</h2></label>
  <input
    type="text"
    name="track[title]"
    id="track_title"
    value="<%=@track.title %>">

  <br><br>

  <label for="track_lyrics"><h2>Lyrics</h2></label>
  <textarea
    rows="10"
    cols="30"
    name="track[lyrics]"
    id="track_lyrics"><%= @track.lyrics %></textarea>

  <br><br>

  <p><h2>Album Type</h2></p>

  <label for="track_status_bonus">Bonus</label>
  <input
    type="radio"
    name="track[status]"
    id="track_status_bonus"
    <% if @track.status == "Bonus" %>
      checked="true"
    <% end %>
    value="Bonus">

  <label for="track_status_regular">Regular</label>
  <input type="radio"
  <% if @track.status == "Regular" %>
    checked="true"
  <% end %>

    name="track[status]"
    id="track_status_regular"
    value="Regular">


  <br><br>

  <input type="submit" value="<%= submit_val %>">

</form>

label_inventory/app/views/tracks/edit.html.erb
<h1>Edit <%= @track.title %>

  <%= render "form" %>

label_inventory/app/views/tracks/new.html.erb
<h1>Add a Track</h1>

<%= render "form" %>

label_inventory/app/views/tracks/show.html.erb
<h1>Track Page for <%= @track.title %> </h1>

<p>Band:  <a href="<%= band_url(@track.band) %>"><%= @track.band.name %></p></a>

<p>Album: <a href="<%= album_url(@track.album) %>">
            <%= @track.album.title %></p>
          </a>

<p>Status: <%= @track.status %></p>

<p>Lyrics: <%= @track.lyrics %></p>

<h2>Notes</h2>
<% if @track.notes.any? %>
  <ul>
    <% @track.notes.each do |note| %>
    <li><%= render note %></li>
    <%= render "helpers/destroynote", note: note %>
    <% end %>
  </ul>
<% else %>
  <p>(None)</p>
<% end %>

<form action="<%= track_notes_url(@track) %>" method="POST">
  <%= render "helpers/auth" %>

  <label>Note:
    <textarea name="note[body]"></textarea>
  </label>

  <input type="submit" value="Add Note">
</form>

<a href="<%= edit_track_url(@track) %>">Edit this Track</a>
<br><br>

<form action="<%= track_url(@track) %>" method="post">
  <input type="hidden" name="_method" value="delete">

 <%= render "helpers/auth" %>

  <input type="submit" value="Delete This Track">

</form>