label_inventory/config/routes.rb
LabelInventory::Application.routes.draw do

  resources :users do
    collection do
      get 'activate'
    end
  end
  resource :session, only: [:create, :destroy, :new]

  resources :bands do
    resources :albums, only: [:new, :create, :index]
    resources :tracks, only: [:new, :create, :index]
  end

  resources :tracks, only: [:show, :destroy, :update, :edit] do
    resources :notes, only: [:show, :new, :create]
  end

  resources :notes, only: [:destroy]
  resources :albums, only: [:show, :destroy, :update, :edit]

  root to: 'bands#index'
end

label_inventory/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LabelInventory</title>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <header>
      <% if current_user %>
        Welcome <%= current_user.email %>!
        <br>
        <form action="<%= session_url %>" method="post">
          <input type="hidden" name="_method" value="delete">
          <input type="hidden"
            name="authenticity_token"
            value="<%= form_authenticity_token %>">

          <input type="submit" value="Log out!">

        </form>

      <% else %>
        <a href="<%= new_session_url%>">Sign in!</a>

        <a href="<%= new_user_url%>">Sign up!</a>

      <% end %>

      <br><br>
      <strong><%= flash[:errors]%></strong>
    </header>

    <%= yield %>

    <br>
    <br>
    <footer>
      <a href="<%= bands_url%>">Return to Bands Index</a>
    </footer>

  </body>
</html>