label_inventory/config/routes.rb
LabelInventory::Application.routes.draw do

  resources :users do
    collection do
      get 'activate'
    end
  end
  resource :session, only: [:create, :destroy, :new]

  resources :bands do
    resources :albums, only: [:new, :create, :index]
    resources :tracks, only: [:new, :create, :index]
  end

  resources :tracks, only: [:show, :destroy, :update, :edit] do
    resources :notes, only: [:show, :new, :create]
  end

  resources :notes, only: [:destroy]
  resources :albums, only: [:show, :destroy, :update, :edit]

  root to: 'bands#index'
end

label_inventory/app/models/band.rb
class Band < ActiveRecord::Base

  validates :name, presence: true

  has_many :albums, dependent: :destroy
  has_many :tracks, through: :albums, source: :recordings, dependent: :destroy

end

label_inventory/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band.id)
    else
      flash[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def show
    @band = Band.find(params[:id])
  end

  def edit
    @band = Band.find(params[:id])
  end

  def update
    @band = Band.find(params[:id])
    if @band.update_attributes(band_params)
      flash[:notices] = "Successfully Updated!"
      render :show
    else
      flash[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def destroy
    Band.find(params[:id]).destroy
    redirect_to bands_url
  end


  private

  def band_params
    params.require(:band).permit(:name)
  end
end

label_inventory/app/helpers/bands_helper.rb
module BandsHelper
end

label_inventory/app/views/bands/_form.html.erb
<% if @band.persisted? %>
  <% action = band_url(@band) %>
  <% button_name = "Edit Band" %>
<% else %>
  <% action = bands_url %>
  <% button_name = "Create Band" %>
<% end %>



<form action="<%= action %>" method="post">
  <% if @band.persisted? %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <input type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="band_name"><h2>Band Name</h2></label>
  <input type="text" name="band[name]" id="band_name" value="<%= @band.name %>">

  <br><br>
  <input type="submit" value="<%= button_name %>">

</form>

label_inventory/app/views/bands/edit.html.erb
<h1>Edit a Band</h1>

<%= render "form" %>

label_inventory/app/views/bands/index.html.erb
<h1>All Bands</h1>

<ul>
  <% @bands.each do |band|%>
    <li><a href="<%= band_url(band) %>"><%= band.name %></a></li>
  <% end %>
</ul>

<br>
<a href="<%= new_band_url %>">Add a Band</a>

label_inventory/app/views/bands/new.html.erb
<h1>Create a Band</h1>

<%= render "form" %>

label_inventory/app/views/bands/show.html.erb
<h1><%= @band.name%></h1>


<h2>Albums</h2>

<% @band.albums.each do |album| %>
  <h3><a href="<%= album_url(album) %>"><%= album.title %></h3></a>
  <p>Tracks:</p>
  <ul>
    <% album.recordings.each do |recording| %>
      <li>
        <a href="<%= track_url(recording) %>"><%= recording.title%></a>
      </li>
    <% end %>
  </ul>

<% end %>

<br>

<a href="<%= new_band_album_url(@band) %>">Add an Album</a>

<br><br>

<a href="<%= new_band_track_url(@band) %>">Add a Track</a>

<br><br>

<a href="<%= edit_band_url(@band) %>">Edit Band</a>
<form action="<%= band_url(@band) %>" method="post">
  <input type="hidden" name="_method" value="delete">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="submit" value="Delete this Band">

</form>